{{- if .Values.userService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata: 
{{- with .Values.userService }}
  name: {{ .name }}
  labels:
    app: {{ .name }}
spec:
  minReadySeconds: 10
  selector:
    matchLabels:
      app: {{ .name }}
{{- end}}
  relicas: {{ .Values.replicaCount }}
{{- with .Values.userService }}
  strategy: 
    type: RollingUpdate
  template:
    metadata:
      lables:
        app: {{ .name }}
        role: backend
    spec:
      containers:
        - name: {{ .name }}
          image: {{ printf "%s:%s" .image .tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .servicePort }}
          resources:
          requests:
            memory: {{ .resources.requests.memory }}
            cpu: {{ .resources.requests.cpu }}
          limits:
            memory: {{ .resources.limits.memory }}
            cpu: {{ .resources.limits.cpu }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
spec:
  ports:
  - name: http
    port: {{ .servicePort }}
    protocol: TCP
    targetPort: {{ .servicePort }}
  selector:
    app: {{ .name }}
  type: ClusterIP

{{- end }}